package universidadejemgrupo64.Vistas;

import java.awt.Image;
import javax.swing.ImageIcon;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmForAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmForMateria = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jmManejoInsc = new javax.swing.JMenuItem();
        jmManipuNota = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmAlumMateria = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");
        jmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnoActionPerformed(evt);
            }
        });

        jmForAlumno.setText("Formulario de Alumno");
        jmForAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmForAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmForAlumno);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmForMateria.setText("Formulario Materia");
        jmForMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmForMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmForMateria);

        jMenuBar1.add(jmMateria);

        jmAdministracion.setText("Administración");

        jmManejoInsc.setText("Manejo de Inscripciones");
        jmAdministracion.add(jmManejoInsc);

        jmManipuNota.setText("Manipulación de Notas");
        jmManipuNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManipuNotaActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmManipuNota);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmAlumMateria.setText("Alumno por Materia");
        jmAlumMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumMateriaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmAlumMateria);

        jMenuBar1.add(jmConsultas);

        jmSalir.setText("Salir");
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmForAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmForAlumnoActionPerformed
        // TODO add your handling code here:
        

        ///////////// ACA INICIALIZO LA VISTA DEL FORMULARIO DE ALUMNO//////
        
        //////////// RENOMBRE EL JDESKTOPANE COMO escritorio PARA LLAMAR SUS METODOS MAS FACIL
        
        //////////// PRIMERO REMUEVO CUALQUIER COSA QUE HAYA EN EL ESCRITORIO
        escritorio.removeAll();
        //////////// DESPIES REPINTO TODO EL ESCRITORIO
        escritorio.repaint();
        
        /////////// ACA INSTANCIO EL FORMULARIO DE ALUMNO
        FormularioAlumno fa = new FormularioAlumno();
        
        ////////// ACA YA CON EL NUEVO FORMULARIO DE ALUMNO LLAMADO fa LO SETEO EN VISIBLE
        fa.setVisible(true);
        
        ////////// ACA AGREGO A fa AL ESCRITORIO
        escritorio.add(fa);
        
        ///////// ACA MUEVO AL FRENTE A fa
        escritorio.moveToFront(fa);
    }//GEN-LAST:event_jmForAlumnoActionPerformed

    private void jmAlumMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAlumMateriaActionPerformed

    private void jmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmAlumnoActionPerformed

    private void jmForMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmForMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateria fm=new FormularioMateria();
        fm.setVisible(true);
        escritorio.add(fm);
        escritorio.moveToFront(fm);
 
    }//GEN-LAST:event_jmForMateriaActionPerformed

    private void jmManipuNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManipuNotaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargaDeNotas cdn= new CargaDeNotas();
        cdn.setVisible(true);
        escritorio.add(cdn);
        escritorio.moveToFront(cdn);
        
    }//GEN-LAST:event_jmManipuNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenuItem jmAlumMateria;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmForAlumno;
    private javax.swing.JMenuItem jmForMateria;
    private javax.swing.JMenuItem jmManejoInsc;
    private javax.swing.JMenuItem jmManipuNota;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
